### ISSUE TITLE
How about migrating the CI from Travis to Github Actions?

### ISSUE THREAD

**Issue by ilario-pierbattista** [widmogrod/php-monads#109]
Hi,
lately I migrated the CI of some projects of mine from Travis to Github Actions.
The main reason was to escape from the new pricing model of Travis, which gaves to OSS projects a limited amount of free minutes of usage.
But I discovered also that Github Actions are quite faster than Travis.

Could you be interested in them?

**Comment by widmogrod** [comment]
Working on it https://github.com/widmogrod/php-functional/pull/115

**Comment by widmogrod** [comment]
Done
