### ISSUE TITLE
Namespace clash with functional-php

### ISSUE THREAD

**Issue by krtek4** [widmogrod/php-monads#23]
Hello there,

Thanks for the great work on this library, it's nice to have some monad implementation especially based on FantasyLand :)

I have one not so small issue however. I usually like to use https://github.com/lstrojny/functional-php but sadly when installing both packages via composer there is a nameclash on the `invoke` that you both define in the `Functional` namespace.

```
PHP Fatal error:  Cannot redeclare Functional\invoke() (previously declared in /vagrant/src/vendor/lstrojny/functional-php/src/Functional/Invoke.php:37) in /vagrant/src/vendor/widmogrod/php-functional/src/Functional/functions.php on line 94
```

I am not sure what the best solution is. As fas as I know, it is not possible to fix this via composer. I would like to propose a renaming of your namespace as this library is probably less used than "functional-php" thus leading to fewer BC breaks.

I can see two possible renames :
- rename just the `Functional` namespace to something else, like `FunctionalHelpers` for examples. But there might be issues for other namespaces like `Monad` later.
- put everything "under" a parent namespace like `Widmogrod` or something like that.

What do you think ?

I can provide a PR doing all that as soon as we agree on the best solution.

Cheers,

**Comment by widmogrod** [comment]
Hi @krtek4 , good point. IMHO best solution would be to put everything under `Widmogrod` namespace. BC could be solve by semantic versioning.

Best
