### ISSUE TITLE
Writer and Reader monads

### ISSUE THREAD

**Issue by krtek4** [widmogrod/php-monads#28]
Hey,

I have an implementation of the [Writer](https://wiki.haskell.org/All_About_Monads#The_Writer_monad) and [Reader](https://wiki.haskell.org/All_About_Monads#The_Reader_monad) monads that are using the interfaces you defined.

At the time, I didn't write any tests however.

Would you be interested in a PR for those two monads ?

**Comment by widmogrod** [comment]
@krtek4 It would be awesome to have them :) More people could learn why they are useful. Even better would be to have them with some **practical examples** like here https://github.com/widmogrod/php-functional/blob/master/example/StateMonadTest.php - but this is not necessary.

However, code review won't pass without tests, fortunately testing Mondas is easy, especially that in this lib - property tests for monads are defined (https://github.com/widmogrod/php-functional/blob/master/src/Helpful/MonadLaws.php) and easy to use.

Complete example: https://github.com/widmogrod/php-functional/blob/master/test/Monad/StateTest.php

**Comment by krtek4** [comment]
Ok great !

I already have the examples written and I will write the tests.

Thanks for the pointers to the relevant files :) Expect a PR later this evening.

**Comment by widmogrod** [comment]
Excellent!
