### ISSUE TITLE
use reflection to detect number of arguments for Curry

### ISSUE THREAD

**Issue by safareli** [widmogrod/php-monads#3]
I have used PHP Reflection and implemented version of [Curry](https://gist.github.com/safareli/db10985e6883ed31c54c) without need of explicitly passing number of arguments.

is there any reason of not using this way to detect number of arguments?

**Comment by widmogrod** [comment]
Reflection use more memory, can lead to memory leaks.
Beside that, the function `curryN` gives you more flexibility;

Consider the example.
We have a function with a some default arguments (you have plenty of those in the PHP i.e. `array_filter`, `substr`,...)

``` php
$d = curry(function($a, $defaults = 'a'){
     return $a === 2 ? $defaults : $a;
});
```

Your implementation won't work with such function, because expects to have one more argument.

``` php
assert($d(2) instanceof \Closure);
```

But curryN enables you to be make code that work as you want it:

``` php
$d = curryN(1, function($a, $defaults = 'a'){
     return $a === 2 ? $defaults : $a;
});
assert($d(2) === 'a');
```

Explicit over implicit always wins.
I hope that answers your question.

**Comment by safareli** [comment]
my [implementation](https://gist.github.com/safareli/db10985e6883ed31c54c#file-curry-php-L33) can be used as `curryN` if you pass second argument `$numberOfArguments`

```
$d = curry(function($a, $defaults = 'a'){
     return $a === 2 ? $defaults : $a;
}, 1);
assert($d(2) === 'a');
```

if there are performance problems with reflection user of library could pass `$numberOfArguments` as if he is using `curryN` or if he doesn't cares it will be detected by reflection

**Comment by widmogrod** [comment]
I didn't noticed. 

Your implementation try to solve two problems at once.
Currying and detecting number of arguments of curried function.
In this case I prefere `open close principle` from OOP.
Open for extension & closed for modification.

I would do something like this.
- Left `curryN` as it is.
- Create new `curry` function which could look like this:

``` php
function curry(callable $function, array $args = []) {
   $reflectionOfFunction = new ReflectionFunction($function);
   $numberOfArguments = count($reflectionOfFunction->getParameters());

  return curryN($numberOfArguments, $fn, $args);
}
```

What do you think about this?

**Comment by safareli** [comment]
i think since `curry` uses `curryN` it does not need `$args` in its arguments doesn't it ?

**Comment by widmogrod** [comment]
Well, you don't always want to curry from the first argument:

``` php
$base = curry(function($a, $b, $c) {/**/}, [1, 2]);
$base(1);
$base(2);
// ....
```

So having `$args` is more useful.

**Comment by widmogrod** [comment]
The last question, do you want to include this function in this library?

**Comment by safareli** [comment]
i'll send PR today :3

**Comment by widmogrod** [comment]
Thank you :)

**Comment by slifin** [comment]
It's possible to drop the reflection requirement in curry() by forcing the function consumer to specify all the parameters, replacing any to be filled in later with a placeholder type:

https://gist.github.com/slifin/ebfb3bb084e6633d94fb915e65202791

Unsure if this is helpful though
