### ISSUE TITLE
Listtt - first class citizen 

### ISSUE THREAD

**Issue by widmogrod** [widmogrod/php-monads#46]
**The Problem:**
PHP has native `array` (`[]`) and `\Traversable` types like `Iterator`, `Generator`,...
To be able handle those types in `php-functional` a lot of nasty  work need to be done to work on those types and do conversion between them:
- `toList` - https://github.com/widmogrod/php-functional/blob/master/src/Functional/functions.php#L180
- `toTraversable` https://github.com/widmogrod/php-functional/blob/master/src/Functional/functions.php#L132
- `toFoldable` https://github.com/widmogrod/php-functional/blob/master/src/Functional/functions.php#L113}
- `toNativeTraversable` - https://github.com/widmogrod/php-functional/blob/master/src/Functional/functions.php#L598

This complicates learning path and implementation of many structures in this project.

**A proposed solution:**
My proposition to this problem is to have ONE type `Listt`.
- every function, monad,... would know how to work on this representation
- set of functions would be created to do adapt any `Traversable` type to this structure 

TODO
- [x] standardise api
- [x] add method `head()` to `Listt`
- [x] add method `tail()`to `Listt`
- [x] add functions to adapt native PHP types to `Listt`
- [x] use `Listt` type every ware in project

Draft:

``` php
use Widmogrod\Functional as f;

$list = f\fromNil();
$list = f\prepend(1, $list); // x : xs
$list = f\append($listA, $listB); // xs ++ xs
$list = f\map(add(1), $list);
$head = f\head($list);
$tail = f\tail($list);
```

``` php
use Widmogrod\Functional as f;

$list = f\fromIterable(generate(100));
$list = f\fromIterable([1,2,3]);
$list = f\fromValue(1) // [1]
```

**Comment by slifin** [comment]
array like objects are usually a bad time in PHP land have you considered having a type that simply holds the array? 
You could type against the new data structure, then add a signature for its data (whether it's an array or something else) on opening of the box 
then use new List([1, 2, 3]) or w/e to pack it back into the box

https://3v4l.org/EoG6b

**Comment by tPl0ch** [comment]
@widmogrod Did you think about something along the lines of:

```php
/**
 * push :: [a] -> [a] -> [a]
 *
 * Append Listt with values.
 *
 * @param Listt    $list
 * @param iterable $values
 *
 * @return Listt
 * @throws \Widmogrod\Primitive\TypeMismatchError
 */
function push(Listt $list, iterable $values): Listt
{
    return $list->concat(Listt::of($values));
}
```

**Comment by widmogrod** [comment]
More details here: https://github.com/widmogrod/php-functional/blob/9da94a218c9ad60302c199edb7662df3a99184d7/src/Functional/listt.php
