### ISSUE TITLE
Maybe implementation, magic `null` value

### ISSUE THREAD

**Issue by zerkms** [widmogrod/php-monads#5]
Wouldn't it be better if `Maybe` was implemented the same way as `Either`:

With a generic `Maybe` interface and 2 specialisations `Just` and `Nothing`.

That way we could deal with the actual `null` value as a real value (which it is).

Thoughts?

**Comment by widmogrod** [comment]
Very good point. I'll implement something like this.

**Comment by widmogrod** [comment]
@zerkms PR is ready. Could you review it?

**Comment by zerkms** [comment]
Sure, will do that today

**Comment by zerkms** [comment]
@widmogrod it looks great (but I'm not advanced in theory category)

PS: I've left one comment though

**Comment by widmogrod** [comment]
@zerkms me neither :)

Thanks for review. I removed duplicated test.

If you are interested in this topic, here is great book (very short and concise): https://www.gitbook.com/book/drboolean/mostly-adequate-guide/details

**Comment by zerkms** [comment]
@widmogrod thanks :-) I've read it and I'm following that repository changes :-)
