### ISSUE TITLE
Listt not found, PHP 7.0.14

### ISSUE THREAD

**Issue by CriztianiX** [widmogrod/php-monads#52]
Hey, I've added to my composer.json

>     ...
>     "widmogrod/php-functional": "*"
>     ...

but i get 

> Class 'Widmogrod\Primitive\Listt' not found

when i try to run 

```php
<?php
namespace App\Controller;
use App\Controller\AppController;
use Cake\Core\Configure;
use Widmogrod\Functional as f;
use Widmogrod\Primitive\Listt;

class DebugController extends AppController
{
    public function initialize()
    {
        parent::initialize();
        $this->Auth->allow(['functional']);
    }

    public function functional()
    {
        $list = Listt::of([
            ['id' => 1, 'name' => 'One'],
            ['id' => 2, 'name' => 'Two'],
            ['id' => 3, 'name' => 'Three'],
        ]);
        exit();
    }
}
```

**Comment by widmogrod** [comment]
Unfortunately I cannot confirm this.

What I did:
- checkout latest version
- install composer dependencies
- run tests

and everything works.

I you could provide me means to reproduce I could help to solve it.
Maybe issue is with composer autoloader cache?
