### ISSUE TITLE
Explicit minimum PHP version

### ISSUE THREAD

**Issue by mattjmattj** [widmogrod/php-monads#54]
In #31, @widmogrod said that the minimum PHP version supported is 5.6, referring to the Travis build configuration file.
It would be interesting to explicitly declare it in composer.json

Also note that the current tests are very close to passing on end-of-life PHP 5.5 (tested with PHP 5.5.9-1ubuntu4.20). Only Product and Sum primitives trigger an error due to their constructor, which is both inherited from their parent class Num and from the PointedTrait trait. This seems not to be a problem on more recent PHP versions

**Comment by tPl0ch** [comment]
@widmogrod Since you removed support for PHP 5.6 in the just released 3.1 version, I think a lot of new possibilities open up for this library.

**Comment by widmogrod** [comment]
Absolutely :)
For now small step in that direction https://github.com/widmogrod/php-functional/pull/66
