### ISSUE TITLE
mcompose failure

### ISSUE THREAD

**Issue by ace411** [widmogrod/php-monads#56]
I am trying to use the ```mcompose``` function in the library and failing. I keep getting the following error in my console:

```
PHP Fatal error:  Uncaught Error: Call to undefined function Widmogrod\Functional\mcompose()
```

**Comment by widmogrod** [comment]
error `Call to undefined function` can mean:
- library is not imported i.e. via composer
- library is not added to autoloader i.e. via composer
- there is a problem with namespace i.e.

  ```diff
  -   Widmogrod\Functional\mcompose  
  +   \Widmogrod\Functional\mcompose
   ```

**Comment by ace411** [comment]
I've tried to fix all the possible problems but to no avail. My ```composer.json``` file looks like this:
```
"require-dev": {
        "psr/log": "*",
        "widmogrod/php-functional": "*"
    },
    "autoload": {
        "psr-4": {
            "Widmogrod\\": "vendor/widmogrod/php-functional/src"
        }
    }
```

**Comment by mfdj** [comment]
@ace411 I'm going to guess you probably don't want to add that psr-4 autoloading there, since the `widmogrod/php-functional` defines it's own autoloader, see: https://github.com/widmogrod/php-functional/blob/master/composer.json#L23

I cooked up a minimum viable example:

```json
{
    "require": {
        "psr/log": "*",
        "widmogrod/php-functional": "*"
    }
}
```

```php
<?php

require __DIR__ . '/vendor/autoload.php';

\Widmogrod\Functional\mcompose(function() {
    // …
}, function() {
    // …
});
```

That should run without error.

**Comment by widmogrod** [comment]
I agree with @mfdj.

In addition tho that. I recommend use of composer command line tool instead of fixing your own `composer.json` by hand

The easiest and safest way to add library to composer is to jut run:
```
composer require widmogrod/php-functional
```

**Comment by ace411** [comment]
Thanks a lot, everyone. I was able to fix the problem.

**Comment by ace411** [comment]
Might I recommend building a simple search engine for all the functions available? I'm talking about something like Hoogle for Haskell; maybe Poogle for PHP? I can take on this responsibility if you are indeed willing to delegate the responsibility to me.

**Comment by widmogrod** [comment]
> I can take on this responsibility if you are indeed willing to delegate the responsibility to me.

@ace411 If you have an idea how to build something like this go for it! community will be grateful to you :)
