### ISSUE TITLE
Extract FantasyLand to separate project

### ISSUE THREAD

**Issue by widmogrod** [widmogrod/php-monads#81]
@krtek4 WDYT to put it to the https://github.com/functional-php organisation?
(as you suggested in your book)

**Comment by krtek4** [comment]
Yeah, seems like a great idea :)

I don't have much time to take care of those kind of stuff right now, tho, but I just made you owner of the organisation so you can create any repo you want there :)

Let me know if I can help in any manner.

**Comment by widmogrod** [comment]
@krtek4 Thank you! I will use granddad power wisely ;)

**Comment by krtek4** [comment]
I trust you to do the right thing son !

**Comment by widmogrod** [comment]
First pull request is waiting https://github.com/functional-php/fantasy-land/pull/7
