### ISSUE TITLE
liftM2 documentation seems not coherent with its implementation

### ISSUE THREAD

**Issue by ilario-pierbattista** [widmogrod/php-monads#97]
Hi,

I was looking to the documentation of `liftM2`:
https://github.com/widmogrod/php-functional/blob/e5f9d609077dbaf806b2d56967153e72a044a10c/src/Functional/functions.php#L384
which is similar to the [haskell version](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Monad.html#v:liftM2).

However the implementation seems to be wrong: `$transformation` is not used as a pure function.

https://github.com/widmogrod/php-functional/blob/e5f9d609077dbaf806b2d56967153e72a044a10c/src/Functional/functions.php#L396-L415

It seems to be like [bind2](https://hackage.haskell.org/package/util-0.1.13.0/docs/Util.html#v:bind2).
Am I missing something?

Thanks

**Comment by widmogrod** [comment]
@ilario-pierbattista grate finding! You're correct. 

To make implementation valid. This change is required:
```diff
-return $transformation($a, $b); 
+return $ma::of($transformation($a, $b));
```

**Comment by ilario-pierbattista** [comment]
Why not just changing the latest `bind` to a `map`?

**Comment by widmogrod** [comment]
There are many roads to Rome. No particular reason.
